# Generated by Django 3.0.7 on 2020-06-26 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['nome'], 'permissions': (('permissao_editar', 'Pode editar cursos'), ('pode_fazer_outra_coisa', 'Pode fazer outra coisa'))},
        ),
    ]
