# Generated by Django 3.0.7 on 2020-06-26 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200626_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplinasinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'Aberta'), ('f', 'Fechada'), ('e', 'Execução'), ('l', 'Finalizada')], default='f', help_text='Book availability', max_length=1),
        ),
    ]
