# Generated by Django 3.0.7 on 2020-06-26 19:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_auto_20200626_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinasinstance',
            name='alunos',
            field=models.ManyToManyField(limit_choices_to={'groups__name': 'Alunos'}, related_name='Alunos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='disciplinas',
            name='requisitos',
        ),
        migrations.AddField(
            model_name='disciplinas',
            name='requisitos',
            field=models.ManyToManyField(blank='true', null='true', related_name='_disciplinas_requisitos_+', to='app.Disciplinas'),
            preserve_default='true',
        ),
        migrations.AlterField(
            model_name='disciplinasinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'Aberta'), ('f', 'Fechada'), ('e', 'Execução'), ('l', 'Finalizada')], default='f', help_text='Status da Disciplina', max_length=1),
        ),
    ]
