# Generated by Django 3.0.7 on 2020-06-26 19:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_auto_20200626_1641'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DisciplinasInstance',
            new_name='DisciplinaInstance',
        ),
    ]
