# Generated by Django 3.0.7 on 2020-06-26 21:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_auto_20200626_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplinainstance',
            name='alunos',
            field=models.ManyToManyField(blank=True, limit_choices_to={'groups__name': 'Alunos'}, related_name='Alunos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='disciplinainstance',
            name='id',
            field=models.UUIDField(help_text='ID da Disciplina', primary_key=True, serialize=False),
        ),
    ]
