# Generated by Django 3.0.7 on 2020-06-26 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0010_auto_20200626_1823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disciplinas',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='disciplinas',
            name='alunos',
            field=models.ManyToManyField(blank=True, limit_choices_to={'groups__name': 'Alunos'}, related_name='Alunos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disciplinas',
            name='prof',
            field=models.ForeignKey(default=1, limit_choices_to={'groups__name': 'Professores'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disciplinas',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'Aberta'), ('f', 'Fechada'), ('e', 'Execução'), ('l', 'Finalizada')], default='f', help_text='Status da Disciplina', max_length=1),
        ),
        migrations.DeleteModel(
            name='DisciplinaInstance',
        ),
    ]
