# Generated by Django 3.0.7 on 2020-07-18 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0012_auto_20200626_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('requisitos', models.ManyToManyField(blank=True, null=True, to='app.Disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='DisciplinasInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('a', 'Aberta'), ('f', 'Fechada'), ('e', 'Execução'), ('l', 'Finalizada')], default='f', help_text='Status da Disciplina', max_length=1)),
                ('alunos', models.ManyToManyField(blank=True, limit_choices_to={'groups__name': 'Alunos'}, related_name='Alunos', to=settings.AUTH_USER_MODEL)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Disciplina')),
                ('prof', models.ForeignKey(limit_choices_to={'groups__name': 'Professores'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='Disciplinas',
        ),
        migrations.AlterField(
            model_name='curso',
            name='disciplinas',
            field=models.ManyToManyField(to='app.Disciplina'),
        ),
    ]
